from flask import Flask, render_template, Markup, request, redirect, url_for, session
import pandas as pd
import re
import os

projects = [
    {'id' :1, 'name' : 'IFG'},
    {'id' :2, 'name' : 'CCEP'}
]



dashboards = [
    {'id' : 1, 'name' : 'COVID 19 Dashboard', 'embed_code' : '<div class=\'tableauPlaceholder\' id=\'viz1678173802964\' style=\'position: fixed; left: 100px; align-items: center;\'><noscript><a href=\'#\'><img alt=\'Dashboard 1 \' src=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Co&#47;Covid19Analysis_16384409277360&#47;Dashboard1&#47;1_rss.png\' style=\'border: none\' /></a></noscript><object class=\'tableauViz\'  style=\'display:none;\'><param name=\'host_url\' value=\'https%3A%2F%2Fpublic.tableau.com%2F\' /><param name=\'embed_code_version\' value=\'3\' /> <param name=\'site_root\' value=\'\' /><param name=\'name\' value=\'Covid19Analysis_16384409277360&#47;Dashboard1\' /><param name=\'tabs\' value=\'no\' /><param name=\'toolbar\' value=\'yes\' /><param name=\'static_image\' value=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Co&#47;Covid19Analysis_16384409277360&#47;Dashboard1&#47;1.png\' /><param name=\'animate_transition\' value=\'yes\' /><param name=\'display_static_image\' value=\'yes\' /><param name=\'display_spinner\' value=\'yes\' /><param name=\'display_overlay\' value=\'yes\' /><param name=\'display_count\' value=\'yes\' /><param name=\'language\' value=\'en-US\' /></object></div><script type=\'text/javascript\'>var divElement = document.getElementById(\'viz1678173802964\');var vizElement = divElement.getElementsByTagName(\'object\')[0];if ( divElement.offsetWidth > 800 ) { vizElement.style.width=\'1280px\';vizElement.style.height=\'720px\';}else if ( divElement.offsetWidth > 500 ) { vizElement.style.width=\'1280px\';vizElement.style.height=\'720px\';}else{ vizElement.style.width=\'100%\';vizElement.style.height=\'2627px\';}var scriptElement = document.createElement(\'script\');scriptElement.src = \'https://public.tableau.com/javascripts/api/viz_v1.js\';vizElement.parentNode.insertBefore(scriptElement, vizElement);</script>', 'project_id':1},
    {'id' : 2, 'name' : 'CCI Dashboard', 'embed_code' : '<div class=\'tableauPlaceholder\' id=\'viz1678612684508\' style=\'position: fixed; left: 100px; align-items: center;\'><noscript><a href=\'#\'><img alt=\'OECD CCI \' src=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Co&#47;ConsumerConfidenceIndex&#47;OECDCCI&#47;1_rss.png\' style=\'border: none\' /></a></noscript><object class=\'tableauViz\'  style=\'display:none;\'><param name=\'host_url\' value=\'https%3A%2F%2Fpublic.tableau.com%2F\' /><param name=\'embed_code_version\' value=\'3\' /><param name=\'site_root\' value=\'\' /><param name=\'name\' value=\'ConsumerConfidenceIndex&#47;OECDCCI\' /><param name=\'tabs\' value=\'no\' /><param name=\'toolbar\' value=\'yes\' /><param name=\'static_image\' value=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Co&#47;ConsumerConfidenceIndex&#47;OECDCCI&#47;1.png\' /><param name=\'animate_transition\' value=\'yes\' /><param name=\'display_static_image\' value=\'yes\' /><param name=\'display_spinner\' value=\'yes\' /><param name=\'display_overlay\' value=\'yes\' /><param name=\'display_count\' value=\'yes\' /><param name=\'language\' value=\'en-GB\' /></object></div><script type=\'text/javascript\'>var divElement = document.getElementById(\'viz1678612684508\');var vizElement = divElement.getElementsByTagName(\'object\')[0];vizElement.style.width=\'1500px\';vizElement.style.height=\'1100px\';var scriptElement = document.createElement(\'script\');scriptElement.src = \'https://public.tableau.com/javascripts/api/viz_v1.js\';vizElement.parentNode.insertBefore(scriptElement, vizElement);</script>', 'project_id':2},
    {'id' : 3, 'name' : 'Flipkart Smartphones', 'embed_code' :'<div class=\'tableauPlaceholder\' id=\'viz1678941774942\' style=\'position: fixed; left: 100px; align-items: center;\'><noscript><a href=\'#\'><img alt=\'Dashboard 5 \' src=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Fl&#47;FlipkartSmartphones&#47;Dashboard5&#47;1_rss.png\' style=\'border: none\' /></a></noscript><object class=\'tableauViz\'  style=\'display:none;\'><param name=\'host_url\' value=\'https%3A%2F%2Fpublic.tableau.com%2F\' /> <param name=\'embed_code_version\' value=\'3\' /> <param name=\'site_root\' value=\'\' /><param name=\'name\' value=\'FlipkartSmartphones&#47;Dashboard5\' /><param name=\'tabs\' value=\'no\' /><param name=\'toolbar\' value=\'yes\' /><param name=\'static_image\' value=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Fl&#47;FlipkartSmartphones&#47;Dashboard5&#47;1.png\' /> <param name=\'animate_transition\' value=\'yes\' /><param name=\'display_static_image\' value=\'yes\' /><param name=\'display_spinner\' value=\'yes\' /><param name=\'display_overlay\' value=\'yes\' /><param name=\'display_count\' value=\'yes\' /><param name=\'language\' value=\'en-US\' /></object></div>                <script type=\'text/javascript\'>                    var divElement = document.getElementById(\'viz1678941774942\');                    var vizElement = divElement.getElementsByTagName(\'object\')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width=\'1300px\';vizElement.style.height=\'927px\';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width=\'1300px\';vizElement.style.height=\'927px\';} else { vizElement.style.width=\'100%\';vizElement.style.height=\'2627px\';}                     var scriptElement = document.createElement(\'script\');                    scriptElement.src = \'https://public.tableau.com/javascripts/api/viz_v1.js\'; vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>', 'project_id':2},
    {'id' : 4, 'name' : 'Customer Satisfaction', 'embed_code' : '<div class=\'tableauPlaceholder\' id=\'viz1678942701882\' style=\'position: fixed; left: 100px; align-items: center;\'><noscript><a href=\'#\'><img alt=\'Visualizing Survey Data \' src=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Vi&#47;VisualizingSurveyDataCustomerSatisfaction&#47;VisualizingSurveyData&#47;1_rss.png\' style=\'border: none\' /></a></noscript><object class=\'tableauViz\'  style=\'display:none;\'><param name=\'host_url\' value=\'https%3A%2F%2Fpublic.tableau.com%2F\' /> <param name=\'embed_code_version\' value=\'3\' /> <param name=\'site_root\' value=\'\' /><param name=\'name\' value=\'VisualizingSurveyDataCustomerSatisfaction&#47;VisualizingSurveyData\' /><param name=\'tabs\' value=\'no\' /><param name=\'toolbar\' value=\'yes\' /><param name=\'static_image\' value=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Vi&#47;VisualizingSurveyDataCustomerSatisfaction&#47;VisualizingSurveyData&#47;1.png\' /> <param name=\'animate_transition\' value=\'yes\' /><param name=\'display_static_image\' value=\'yes\' /><param name=\'display_spinner\' value=\'yes\' /><param name=\'display_overlay\' value=\'yes\' /><param name=\'display_count\' value=\'yes\' /><param name=\'language\' value=\'en-US\' /></object></div>                <script type=\'text/javascript\'>                    var divElement = document.getElementById(\'viz1678942701882\');                    var vizElement = divElement.getElementsByTagName(\'object\')[0];                    vizElement.style.width=\'1400px\';vizElement.style.height=\'1027px\';                    var scriptElement = document.createElement(\'script\');                    scriptElement.src = \'https://public.tableau.com/javascripts/api/viz_v1.js\';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>', 'project_id':1},
    {'id' : 5, 'name' : 'Visualizing Distribution', 'embed_code' : '<div class=\'tableauPlaceholder\' id=\'viz1678942743085\' style=\'position: fixed; left: 100px; align-items: center;\'><noscript><a href=\'#\'><img alt=\'Dashboard \' src=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Vi&#47;VisualizingDistributionsBoxPlotsBetterAlternatives&#47;Dashboard&#47;1_rss.png\' style=\'border: none\' /></a></noscript><object class=\'tableauViz\'  style=\'display:none;\'><param name=\'host_url\' value=\'https%3A%2F%2Fpublic.tableau.com%2F\' /> <param name=\'embed_code_version\' value=\'3\' /> <param name=\'site_root\' value=\'\' /><param name=\'name\' value=\'VisualizingDistributionsBoxPlotsBetterAlternatives&#47;Dashboard\' /><param name=\'tabs\' value=\'no\' /><param name=\'toolbar\' value=\'yes\' /><param name=\'static_image\' value=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Vi&#47;VisualizingDistributionsBoxPlotsBetterAlternatives&#47;Dashboard&#47;1.png\' /> <param name=\'animate_transition\' value=\'yes\' /><param name=\'display_static_image\' value=\'yes\' /><param name=\'display_spinner\' value=\'yes\' /><param name=\'display_overlay\' value=\'yes\' /><param name=\'display_count\' value=\'yes\' /><param name=\'language\' value=\'en-US\' /></object></div>                <script type=\'text/javascript\'>                    var divElement = document.getElementById(\'viz1678942743085\');                    var vizElement = divElement.getElementsByTagName(\'object\')[0];                    vizElement.style.width=\'1308px\';vizElement.style.height=\'827px\';                    var scriptElement = document.createElement(\'script\');                    scriptElement.src = \'https://public.tableau.com/javascripts/api/viz_v1.js\';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>', 'project_id':2},
    {'id' : 6, 'name' : 'dashboard 1234', 'embed_code' : '<div class=\'tableauPlaceholder\' id=\'viz1679036182111\' style=\'position: fixed; left: 100px; align-items: center;\'><noscript><a href=\'#\'><img alt=\'Main Page \' src=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;on&#47;ongoingDashboard&#47;MainPage&#47;1_rss.png\' style=\'border: none\' /></a></noscript><object class=\'tableauViz\'  style=\'display:none;\'><param name=\'host_url\' value=\'https%3A%2F%2Fpublic.tableau.com%2F\' /> <param name=\'embed_code_version\' value=\'3\' /> <param name=\'site_root\' value=\'\' /><param name=\'name\' value=\'ongoingDashboard&#47;MainPage\' /><param name=\'tabs\' value=\'no\' /><param name=\'toolbar\' value=\'yes\' /><param name=\'static_image\' value=\'https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;on&#47;ongoingDashboard&#47;MainPage&#47;1.png\' /> <param name=\'animate_transition\' value=\'yes\' /><param name=\'display_static_image\' value=\'yes\' /><param name=\'display_spinner\' value=\'yes\' /><param name=\'display_overlay\' value=\'yes\' /><param name=\'display_count\' value=\'yes\' /><param name=\'language\' value=\'en-US\' /></object></div>                <script type=\'text/javascript\'>                    var divElement = document.getElementById(\'viz1679036182111\');                    var vizElement = divElement.getElementsByTagName(\'object\')[0];                    vizElement.style.width=\'1430px\';vizElement.style.height=\'1747px\';                    var scriptElement = document.createElement(\'script\');                    scriptElement.src = \'https://public.tableau.com/javascripts/api/viz_v1.js\';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>', 'project_id':1}
]

df_projects = pd.DataFrame(projects)
df_dashboards = pd.DataFrame(dashboards)
projects_list = df_projects.values.tolist()
dashboards_list = df_dashboards.values.tolist()
app = Flask(__name__)

@app.route('/')
@app.route('/home')
def home():
    return render_template('home.html', projects = projects)

@app.route('/home/<project_id>')
def dashboardlist(project_id):
    print(project_id)
    query = df_dashboards[df_dashboards['project_id'] == int(project_id)]
    results = query.values.tolist()
    print(results)
    return render_template('project.html', results = results, project_id = project_id)

@app.route('/home/<project_id>/<dashboard_id>')
def embeddashboard(project_id, dashboard_id):
    print("project id = " + str(project_id))
    print("dashboard id = " + str(dashboard_id))
    query = df_dashboards[(df_dashboards['project_id'] == int(project_id)) & (df_dashboards['id'] == int(dashboard_id))]
    embed_code = str(query['embed_code'].values.tolist())
    embed_code = embed_code[2:len(embed_code) - 2]
    embed_code = Markup(embed_code)
    return render_template('dashboard.html', embed_code = embed_code)